import {test} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {io} from 'socket.io-client';
const root=fileURLToPath(new URL('..',import.meta.url));
function once(socket,event,predicate=()=>true){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{socket.off(event,listener);reject(Error('Timed out: '+event));},4000);const listener=value=>{if(!predicate(value))return;clearTimeout(timer);socket.off(event,listener);resolve(value);};socket.on(event,listener);});}
async function connect(base,token){const socket=io(base,{autoConnect:false,reconnection:false,auth:{resumeToken:token},transports:['websocket']});const session=once(socket,'session');socket.connect();const data=await session;return {socket,token:data.resumeToken};}
async function emit(socket,event,payload,response,predicate){const result=once(socket,response,predicate);socket.emit(event,payload);return result;}
test('lobby permissions, consent, dice, identity resume and persistence',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'dnd-integration-'));const port=21000+Math.floor(Math.random()*5000);let child;const sockets=[];const boot=async()=>{child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:String(port),DND_STATE_FILE:path.join(dir,'state.json'),MONGODB_URI:''},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let logs='';const timeout=setTimeout(()=>reject(Error('Startup timeout '+logs)),5000);child.stdout.on('data',chunk=>{logs+=chunk;if(logs.includes('Server on')){clearTimeout(timeout);resolve();}});child.on('exit',code=>{clearTimeout(timeout);reject(Error('Startup exit '+code));});});};const stop=async()=>{const closed=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await closed;};try{await boot();const base='http://127.0.0.1:'+port;const gm=await connect(base);sockets.push(gm.socket);await emit(gm.socket,'identify',{name:'GM'},'identified');await emit(gm.socket,'join_lobby',{lobby:'test'},'joined');const player=await connect(base);sockets.push(player.socket);await emit(player.socket,'identify',{name:'Player'},'identified');await emit(player.socket,'join_lobby',{lobby:'test'},'joined');assert.match(await emit(player.socket,'campaign_start',{},'error_message'),/GM only/);assert.match(await emit(player.socket,'identify',{name:'GM'},'error_message'),/Leave/);const dead=await emit(player.socket,'character_upsert',{hp:0,speed:0},'state',s=>s.characters.Player?.hp===0);assert.equal(dead.characters.Player.speed,0);
assert.match(await emit(player.socket,'npc_add',{preset:'Goblin'},'error_message'),/GM only/);
await emit(gm.socket,'gm_notes',{text:'Private secret'},'gm_notes_saved');
const npcState=await emit(gm.socket,'npc_add',{preset:'Goblin'},'state',s=>s.tabletop?.npcs.Goblin);
assert.equal(npcState.tabletop.npcs.Goblin.hp,7);assert.equal(JSON.stringify(npcState).includes('Private secret'),false);
assert.match(await emit(player.socket,'gm_notes',{text:'Forged secret'},'error_message'),/GM only/);
await emit(player.socket,'inventory_add',{name:'Player',item:{name:'Rope',quantity:2}},'state',s=>s.tabletop.inventories.Player?.length===1);
assert.match(await emit(player.socket,'inventory_add',{name:'Goblin',item:{name:'Forged'}},'error_message'),/owner or GM/);
await emit(player.socket,'journal_add',{text:'We found the cave.'},'state',s=>s.tabletop.journal.length===1);
await emit(gm.socket,'campaign_start',{},'state',s=>s.settings.campaignStarted);for(const expression of ['d0','0d6','4d6kh0'])assert.match(await emit(gm.socket,'roll',{expression},'error_message'),/Too big|Keep/);const roll=await emit(gm.socket,'roll',{expression:'4d6kh3'},'roll');assert.equal(roll.used.length,3);assert.equal(roll.total,roll.used.reduce((a,b)=>a+b,0));const requested=await emit(gm.socket,'campaign_choice_request',{choiceId:'c_intro_tavern'},'state',s=>s.pendingChoice);assert.equal(requested.pendingChoice.to,'s_tavern');const accepted=await emit(player.socket,'campaign_choice_ack',{},'state',s=>s.campaign.currentSceneId==='s_tavern');assert.equal(accepted.pendingChoice,null);const resumed=await connect(base,gm.token);sockets.push(resumed.socket);const joined=await emit(resumed.socket,'join_lobby',{lobby:'test'},'joined');assert.equal(joined.username,'GM');assert.equal(joined.gm,'GM');assert.match(await emit(resumed.socket,'campaign_import',{campaign:{scenes:[]}},'error_message'),/scenes/);const exported=await emit(resumed.socket,'campaign_export',{},'campaign_exported');assert.equal(exported.currentSceneId,'s_tavern');await new Promise(r=>setTimeout(r,250));await stop();await boot();const restored=await connect(base,gm.token);sockets.push(restored.socket);const statePromise=once(restored.socket,'state');await emit(restored.socket,'join_lobby',{lobby:'test'},'joined');const state=await statePromise;assert.equal(state.gm,'GM');assert.equal(state.characters.Player.hp,0);assert.equal(state.campaign.currentSceneId,'s_tavern');assert.equal(state.tabletop.npcs.Goblin.hp,7);assert.equal(state.tabletop.inventories.Player[0].name,'Rope');assert.equal(state.tabletop.journal[0].text,'We found the cave.');const privateData=once(restored.socket,'gm_private');restored.socket.emit('journal_add',{text:'Restored.'});assert.equal((await privateData).notes,'Private secret');}finally{for(const s of sockets)s.disconnect();if(child?.exitCode===null)await stop();await fs.rm(dir,{recursive:true,force:true});}});
